# Mau Source Code ?
# Subscribe Channel Youtube Dan Follow Github Gua Dulu Dong Slur !!!
# Github  :  https://github.com/RSPLOIT-ID
# Youtube :  Rsploit Official
# Udah Langsung Inbox Gua Di > 082259177732

import base64
exec(base64.b32decode("EMQEQYLZPF2SATLBOUQE4Z3FOJSWG33EMUQFSYJAH4FCGICUOVVWC3THEBJGKY3PMRSSAS3PNZ2G63BMEBCWY5JAIVSGS5BAJZUSARTJNRSSATLBNVYG64ZAJR2QUIZAJVQXI2JAJRXSAQLONJUW4ZZAEEQSCIBKL4VAUCTJNVYG64TUEBXXGCTPOMXHG6LTORSW2KBCOB4XI2DPNYZCALTFPBSWGIRJBI======"))
